name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # main 브랜치에 push될 때 워크플로우 실행
    paths-ignore:
      - 'deploy/**'  # deploy 폴더의 변경사항 무시
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: devjyk/exporter:latest

    - name: Logout from Docker Hub
      run: docker logout

    - name: Send Slack Notification
      uses: 8398a7/action-slack@v3
      with:
        status: custom
        fields: workflow,job,commit,repo,ref,author,took
        custom_payload: |
          {
            "text": "Completed",
            "attachments": [{
              "color": "good",
              "text": "${{ github.event.head_commit.message }}"
            }]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}